name: Daily Loyverse Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 08:00 PH time
  workflow_dispatch:     # Manual run option

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas google-cloud-bigquery pyarrow

      - name: Decode and set up GCP credentials
        run: |
          echo "${{ secrets.GCP_KEY_B64 }}" | base64 --decode > gcp_key.json
        env:
          GCP_KEY_B64: ${{ secrets.GCP_KEY_B64 }}

      - name: Run daily Loyverse pull
        env:
          LOYVERSE_TOKEN: ${{ secrets.LOYVERSE_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: gcp_key.json
        run: |
          python daily_loyverse_pull.py
