name: Loyverse Daily Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC (8AM PH time)
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas google-cloud-bigquery pyarrow

      - name: Decode and set up GCP credentials
        run: |
          echo "${{ secrets.GCP_KEY_B64 }}" | base64 --decode > gcp_key.json
        env:
          GCP_KEY_B64: ${{ secrets.GCP_KEY_B64 }}

      - name: Run shift fix
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcp_key.json
        run: python fix_shifts_cash_movements.py
