name: Jibble Attendance Daily

on:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC = 08:00 PH daily
  workflow_dispatch:
    inputs:
      start_date:
        description: "YYYY-MM-DD (optional)"
        required: false
      end_date:
        description: "YYYY-MM-DD (optional)"
        required: false

concurrency:
  group: jibble-attendance
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # gcloud CLI so we can use bq
      - name: Setup gcloud (CLI only)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate gcloud with base64 key
        shell: bash
        run: |
          echo "${{ secrets.GCP_KEY_B64 }}" | base64 -d > "${HOME}/gcp.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp.json"
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      # --- Probe Jibble OData for known day ---
      - name: Probe Jibble OData for a known day
        shell: bash
        env:
          JIBBLE_API_KEY_ID: ${{ secrets.JIBBLE_API_KEY_ID }}
          JIBBLE_API_KEY_SECRET: ${{ secrets.JIBBLE_API_KEY_SECRET }}
          JIBBLE_ORG_ID: ${{ secrets.JIBBLE_ORG_ID }}
        run: |
          set -e
          DAY="2025-09-28"   # << change this to a day you know has punches
          FROM="${DAY}T00:00:00+08:00"
          TO="${DAY}T23:59:59+08:00"

          base="https://workspace.prod.jibble.io"
          org="${JIBBLE_ORG_ID}"
          id="${JIBBLE_API_KEY_ID}"
          secret="${JIBBLE_API_KEY_SECRET}"
          basic=$(printf "%s" "${id}:${secret}" | base64)

          probe() {
            name="$1"
            url="$2"
            echo "---- ${name} ----"
            echo "GET $url"
            curl -sS "$url" \
              -H "Accept: application/json" \
              -H "OData-Version: 4.0" \
              -H "Authorization: Basic ${basic}" \
              -H "X-Organization-Id: ${org}" \
              -D /tmp/h.txt | head -c 600 || true
            echo
            head -n 1 /tmp/h.txt || true
            echo
          }

          # Try BOTH common timestamp fields and path styles
          probe "slash-startedAt" \
            "${base}/v1/Organizations/${org}/TimeEntries?\$filter=startedAt ge ${FROM} and startedAt le ${TO}&\$top=5&\$format=json"

          probe "slash-startAt" \
            "${base}/v1/Organizations/${org}/TimeEntries?\$filter=startAt ge ${FROM} and startAt le ${TO}&\$top=5&\$format=json"

      # ---- Jibble → BigQuery ----
      - name: Sync Jibble Attendance to BigQuery (raw)
        env:
          JIBBLE_API_KEY_ID: ${{ secrets.JIBBLE_API_KEY_ID }}
          JIBBLE_API_KEY_SECRET: ${{ secrets.JIBBLE_API_KEY_SECRET }}
          JIBBLE_ORG_ID: ${{ secrets.JIBBLE_ORG_ID }}

          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          BQ_DATASET: sbco_ops_jibble
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}

          JIBBLE_API_BASE: https://workspace.prod.jibble.io
          JIBBLE_ENTRIES_PATH: /v1/time-entries   # placeholder; script auto-switches when workspace API detected
        run: python sync_jibble_attendance.py

      - name: MERGE raw → final
        run: bq query --quiet --use_legacy_sql=false < merge_final.sql
