name: Jibble Attendance Daily

on:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC = 08:00 PH daily
  workflow_dispatch:
    inputs:
      start_date:
        description: "YYYY-MM-DD (optional)"
        required: false
      end_date:
        description: "YYYY-MM-DD (optional)"
        required: false

concurrency:
  group: jibble-attendance
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # gcloud CLI so we can use bq
      - name: Setup gcloud (CLI only)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate gcloud with base64 key
        shell: bash
        run: |
          echo "${{ secrets.GCP_KEY_B64 }}" | base64 -d > "${HOME}/gcp.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp.json"
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      # --- Probe Jibble OData for known day ---
      - name: Probe Jibble OData (show status + body, try auth variants)
        shell: bash
        env:
          JIBBLE_API_KEY_ID: ${{ secrets.JIBBLE_API_KEY_ID }}
          JIBBLE_API_KEY_SECRET: ${{ secrets.JIBBLE_API_KEY_SECRET }}
          JIBBLE_ORG_ID: ${{ secrets.JIBBLE_ORG_ID }}
        run: |
          set -euo pipefail
          DAY="2025-09-28"   # <-- change to a date that definitely has punches
          FROM="${DAY}T00:00:00+08:00"
          TO="${DAY}T23:59:59+08:00"

          base="https://workspace.prod.jibble.io"
          org="${JIBBLE_ORG_ID}"
          id="${JIBBLE_API_KEY_ID}"
          secret="${JIBBLE_API_KEY_SECRET}"
          basic=$(printf "%s" "${id}:${secret}" | base64)

          probe() {
            label="$1"; field="$2"; auth_hdr="$3"
            echo "---- ${label} (${field}) ----"
            code=$(curl -sS -G "${base}/v1/Organizations/${org}/TimeEntries" \
              --data-urlencode "\$filter=${field} ge ${FROM} and ${field} le ${TO}" \
              --data-urlencode "\$orderby=${field} asc" \
              --data-urlencode "\$top=5" \
              --data-urlencode "\$format=json" \
              -H "Accept: application/json" \
              -H "OData-Version: 4.0" \
              -H "X-Organization-Id: ${org}" \
              -H "${auth_hdr}" \
              -o /tmp/body.json -w "%{http_code}") || true
            echo "HTTP ${code}"
            head -c 800 /tmp/body.json; echo
            echo
          }

          # Also probe the organization object itself to confirm auth
          echo "---- org probe (Basic) ----"
          code=$(curl -sS "${base}/v1/Organizations/${org}" \
            -H "Accept: application/json" \
            -H "OData-Version: 4.0" \
            -H "Authorization: Basic ${basic}" \
            -H "X-Organization-Id: ${org}" \
            -o /tmp/org.json -w "%{http_code}") || true
          echo "HTTP ${code}"
          head -c 800 /tmp/org.json; echo; echo

          # Try time entries with two timestamp fields and two auth styles
          probe "startedAt + Basic" "startedAt" "Authorization: Basic ${basic}"
          probe "startAt  + Basic" "startAt"  "Authorization: Basic ${basic}"

          # Some tenants prefer ApiKey instead of Basic on workspace:
          probe "startedAt + ApiKey" "startedAt" "Authorization: ApiKey ${secret}"
          probe "startAt  + ApiKey" "startAt"  "Authorization: ApiKey ${secret}"



      # ---- Jibble → BigQuery ----
      - name: Sync Jibble Attendance to BigQuery (raw)
        env:
          JIBBLE_API_KEY_ID: ${{ secrets.JIBBLE_API_KEY_ID }}
          JIBBLE_API_KEY_SECRET: ${{ secrets.JIBBLE_API_KEY_SECRET }}
          JIBBLE_ORG_ID: ${{ secrets.JIBBLE_ORG_ID }}

          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          BQ_DATASET: sbco_ops_jibble
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}

          JIBBLE_API_BASE: https://workspace.prod.jibble.io
          JIBBLE_ENTRIES_PATH: /v1/time-entries   # placeholder; script auto-switches when workspace API detected
        run: python sync_jibble_attendance.py

      - name: MERGE raw → final
        run: bq query --quiet --use_legacy_sql=false < merge_final.sql
