name: Jibble Attendance Daily

on:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC = 08:00 PH daily
  workflow_dispatch:
    inputs:
      start_date:
        description: "YYYY-MM-DD (optional)"
        required: false
      end_date:
        description: "YYYY-MM-DD (optional)"
        required: false

concurrency:
  group: jibble-attendance
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Use your existing BASE64 key (GCP_KEY_B64)
      - name: Setup gcloud (CLI only)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate gcloud with base64 key
        shell: bash
        run: |
          echo "${{ secrets.GCP_KEY_B64 }}" | base64 -d > "${HOME}/gcp.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp.json"
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      # --- Preflight: find the correct OAuth token endpoint ---
      - name: Debug Jibble token endpoints
        shell: bash
        env:
          JIBBLE_CLIENT_ID: ${{ secrets.JIBBLE_CLIENT_ID }}
          JIBBLE_CLIENT_SECRET: ${{ secrets.JIBBLE_CLIENT_SECRET }}
        run: |
          set -e
          for u in \
            "https://api.jibble.io/api/oauth/token" \
            "https://api.jibble.io/api/oauth2/token" \
            "https://api.jibble.io/oauth/token" \
            "https://api.jibble.io/oauth2/token"
          do
            echo "POST $u"
            curl -sS -X POST "$u" \
              -d "grant_type=client_credentials&client_id=${JIBBLE_CLIENT_ID}&client_secret=${JIBBLE_CLIENT_SECRET}" \
              -D /tmp/h.txt | head -c 300 || true
            echo
            echo "---- status ----"
            head -n 1 /tmp/h.txt || true
            echo
          done

      - name: Sync Jibble
        env:
          JIBBLE_API_KEY_ID: ${{ secrets.JIBBLE_API_KEY_ID }}
          JIBBLE_API_KEY_SECRET: ${{ secrets.JIBBLE_API_KEY_SECRET }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          BQ_DATASET: sbco_ops_jibble
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}
          JIBBLE_API_BASE: https://api.jibble.io/api
          JIBBLE_ENTRIES_PATH: /v1/time-entries
        run: python sync_jibble_attendance.py

      - name: MERGE to final
        run: bq query --quiet --use_legacy_sql=false < merge_final.sql
