# .github/workflows/weekly-report.yml

name: Weekly Sales Anomaly Report

# This controls when the action will run.
on:
  # Triggers the workflow every Monday at 8:00 AM Manila time (00:00 UTC).
  schedule:
    - cron: '0 0 * * 1'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-send-report:
    runs-on: ubuntu-latest # Use a standard Linux virtual machine

    steps:
      # Step 1: Checks out your repository's code so the job can access it
      - name: Check out repository
        uses: actions/checkout@v4

# Step 2: Set up Google Cloud authentication
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      # Step 3: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the Python script to generate and email the report
      - name: Run Anomaly Detection and Send Email
        env:
          # Pass the GitHub secrets to the Python script as environment variables
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: python main.py
